ALTER TABLE "Sale" ADD COLUMN "partyId" INTEGER;

ALTER TABLE "Sale" ADD COLUMN "partyName" TEXT;

ALTER TABLE "Sale" ADD COLUMN "perSaleProfit" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Party" ADD COLUMN "totalSalesProfit" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Sale" ADD CONSTRAINT "Sale_partyId_fkey" FOREIGN KEY ("partyId") REFERENCES "Party"("id") ON DELETE SET NULL ON UPDATE CASCADE;